### PR TITLE
Represents a forward action

### PR DESCRIPTION
**Pull request by sawanoboly**
Hi, I would like to Represents a forward action in PendingConnection.

This function is working fine with my project. https://github.com/higanworks/knife-zero/blob/master/lib/knife-zero/net-ssh-multi-patch.rb

### CODE REVIEW

**Comment by sawanoboly** [comment]
@mfazekas 
Hi, if you wouldn't mind, would you be able to review it?

**Comment by mfazekas** [comment]
:+1: thanks for the patch

**Comment by sawanoboly** [comment]
@mfazekas Thanks a lot! Can you release new version ?

**Comment by mfazekas** [comment]
@sawanoboly i have no permission, @delano  can you please release? i've prepped everything for 1.3.0.rc1

**Comment by mfazekas** [comment]
https://rubygems.org/gems/net-ssh-multi/versions/1.3.0.rc1 was released

**Pull request merged**
